web:
    build: ./web
    ports:
       - "5000:5000"
    volumes:
       - ./web:/code
    links:
       - postgres
    env_file: .env
postgres:
    image: postgres:latest
    ports:
        - "5432:5432"
